language: ruby
bundler_args: --without development production staging --deployment
rvm:
  - 2.1.0
  - 2.1.1
  - 2.0.0
before_script:
  - cp config/database.yml.ci config/database.yml
  - mysql -e 'create database master_chef_test'
  - psql -c 'create database master_chef_test' -U postgres
env:
  - DB=postgresql
