common:
  title: Master Chef
  host: lvh.me:3000
  default_from_email: "'MasterChef' <no-reply@masterchef.io>"

  mailer:
    delivery_method: test
    smtp_settings:
      user_name: <%= ENV['MAILER_USERNAME'] %>
      password:  <%= ENV['MAILER_PASSWORD'] %>
      address:   <%= ENV['MAILER_HOST'] %>
      port:      <%= ENV['MAILER_PORT'] %>
      authentication: plain

  devise:
    secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  google_analitycs:
    tracking_id: <%= ENV['GA_TRACK_ID'] %>

  pusher_key: <%= ENV['PUSHER_KEY'] %>

test:
  mailer:
    delivery_method: :test

development:
  mailer:
    delivery_method: :test

staging:
  mailer:
    delivery_method: :smtp

  host: master-chef-master.herokuapp.com

production:
  mailer:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      domain: masterchef.io

  host: masterchef.io
