common:
  host: lvh.me:3000
  url_with_port: http://lvh.me:3000
  default_from_email: "'MasterChef' <no-reply@masterchef.io>"

  mailer:
    delivery_method: test
    smtp_settings:
      user_name: <%= ENV['MAILER_USERNAME'] %>
      password: <%= ENV['MAILER_PASSWORD'] %>
      address: falcon.rw.rw
      port: 2525
      authentication: plain

  devise:
    secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  google_analitycs:
    tracking_id: XXXXXXXX

  pusher_key: <%= ENV['PUSHER_KEY'] %>

test:
  mailer:
    delivery_method: :test

development:
  mailer:
    delivery_method: :test

staging:
  mailer:
    delivery_method: :smtp

  host: master-chef-master.herokuapp.com

production:
  bcc: master-chef@jetthoughts.com
  mailer:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.sendgrid.net
      port: 587
      authentication: plain
      enable_starttls_auto: true
      domain: masterchef.io

  host: masterchef.io
