common:
  host: lvh.me:3000
  url_with_port: http://lvh.me:3000
  default_from_email: "'MasterChef' <master_chef@jetthoughts.com>"

  mailer:
    delivery_method: test
    smtp_settings:
      user_name: 4881eb6270ce01
      password: cf3ba842ae5bae
      address: falcon.rw.rw
      port: 2525
      authentication: plain

  devise:
    secret_key: 2f6ca824aaa49fd4c6517b1791317c72a80793918d488cf3a9995493cefdb9767569f61e214108346d49e3f24dfa3b428fa5c2ca33bb4a85951bde29bba19ba0


test:
  mailer:
    delivery_method: :test

development:
  mailer:
    delivery_method: :test

staging:
  mailer:
    delivery_method: :smtp

  host: master-chef-master.herokuapp.com

production:
  do_send_email: true
  bcc: master-chef@jetthoughts.com
  mailer:
    delivery_method: :smtp

  host: master-chef-production.herokuapp.com
